# Generated by Django 5.2.8 on 2025-11-24 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigIntegerField(db_column='idpelicula', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre', max_length=255)),
                ('director', models.CharField(blank=True, db_column='director', max_length=50, null=True)),
                ('productora', models.CharField(blank=True, db_column='productora', max_length=100, null=True)),
                ('año', models.SmallIntegerField(blank=True, db_column='año', null=True)),
                ('calificacion', models.FloatField(blank=True, db_column='calificacion', null=True)),
                ('poster', models.CharField(blank=True, db_column='poster', max_length=50, null=True)),
                ('trailer', models.CharField(blank=True, db_column='trailer', max_length=50, null=True)),
            ],
            options={
                'db_table': 'pelicula',
                'managed': False,
            },
        ),
    ]
