# Generated by Django 5.2.8 on 2025-11-24 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id_comentario', models.BigIntegerField(db_column='idcomentario', primary_key=True, serialize=False)),
                ('calificacion', models.BigIntegerField(db_column='calificacion')),
                ('texto', models.CharField(blank=True, db_column='texto', max_length=500, null=True)),
            ],
            options={
                'db_table': 'comentario',
                'managed': False,
            },
        ),
    ]
