# Generated by Django 5.2.8 on 2025-11-24 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.CharField(db_column='idusuario', max_length=15, primary_key=True, serialize=False)),
                ('password', models.CharField(db_column='password', max_length=255)),
                ('nombre', models.CharField(blank=True, db_column='nombre', max_length=50, null=True)),
                ('apellido_paterno', models.CharField(blank=True, db_column='apellidopaterno', max_length=50, null=True)),
                ('apellido_materno', models.CharField(blank=True, db_column='apellidomaterno', max_length=50, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, db_column='fechanacimiento', null=True)),
                ('genero', models.CharField(blank=True, db_column='genero', max_length=1, null=True)),
                ('token', models.CharField(blank=True, db_column='token', max_length=255, null=True)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
